# Generated by Django 4.0 on 2024-08-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentar',
            old_name='comentario',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='comentar',
            name='comentario_aprobado',
        ),
    ]
